/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include<stdio.h>
#include<stdlib.h>
#include "add.h"


void
addprog_1(char *host, char* testfile)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, ADDPROG, ADDVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	FILE* fptr;
	fptr = fopen(testfile, "r");

	int tot;
	fscanf(fptr, "%d", &tot);
	for(int i = 0; i < tot; i++) {
		int x, y;
		if(fscanf(fptr, "%d%d", &x, &y) != 2) {
			printf("Wrong input type of format!\n");
			break;
		}
		result_1 = add_1(x, y, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else {
			printf("Got Ans: %d\n", *result_1);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	host = (char*)"rpc-server";

	if (argc != 2) {
		printf ("usage: %s ${testfile}\n", argv[0]);
		exit (1);
	}
	addprog_1 (host, argv[1]);
exit (0);
}
